"""
This is a setup.py script generated by py2app and
customized by HASII

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['PyGitIssue2Todoist.py']
DATA_FILES = [('pygitissue2todoist/resources', ['pygitissue2todoist/resources/loggingConfiguration.json']),
              ('pygitissue2todoist/resources', ['pygitissue2todoist/resources/play.png']),
              ('pygitissue2todoist/resources', ['pygitissue2todoist/resources/version.txt']),
              ('pygitissue2todoist/resources', ['pygitissue2todoist/resources/packageversions.txt']),
              ('pygitissue2todoist/resources', ['pygitissue2todoist/resources/SimpleHelp.html'])
              ]
OPTIONS = {}

setup(
    name='PyGitIssue2Todoist',
    version='1.0.0+.17',
    app=APP,
    data_files=DATA_FILES,
    packages=['pygitissue2todoist',
              'pygitissue2todoist.general',
              'pygitissue2todoist.general.exceptions',
              'pygitissue2todoist.resources',
              'pygitissue2todoist.ui',
              'pygitissue2todoist.ui.dialogs'
              ],
    include_package_data=True,
    zip_safe=False,

    url='https://github.com/hasii2011/gittodoistclone',
    author='Humberto A. Sanchez II',
    author_email='Humberto.A.Sanchez.II@gmail.com',
    description='Convert Github issues to Todoist Tasks',
    options={},
    setup_requires=['py2app'],
    install_requires=['wxPython==4.2.1', 'PyGithub==2.2.0', 'todoist-api-python==2.1.3']
)
