"""
This is a setup.py script generated by py2app and
customized by HASII

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['PyGitIssue2Todoist.py']
DATA_FILES = [('gittodoistclone/resources', ['gittodoistclone/resources/loggingConfiguration.json']),
              ('gittodoistclone/resources', ['gittodoistclone/resources/play.png']),
              ('gittodoistclone/resources', ['gittodoistclone/resources/version.txt']),
              ('gittodoistclone/resources', ['gittodoistclone/resources/packageversions.txt']),
              ('gittodoistclone/resources', ['gittodoistclone/resources/SimpleHelp.html'])
              ]
OPTIONS = {}

setup(
    name='PyGitIssue2Todoist',
    version='1.0.0',
    app=APP,
    data_files=DATA_FILES,
    packages=['gittodoistclone',
              'gittodoistclone.general',
              'gittodoistclone.general.exceptions',
              'gittodoistclone.resources',
              'gittodoistclone.ui',
              'gittodoistclone.ui.dialogs'
              ],
    include_package_data=True,
    zip_safe=False,

    url='https://github.com/hasii2011/gittodoistclone',
    author='Humberto A. Sanchez II',
    author_email='Humberto.A.Sanchez.II@gmail.com',
    description='Convert Github issues to Todoist Tasks',
    options={},
    setup_requires=['py2app'],
    install_requires=['wxPython', 'PyGithub', 'todoist-api-python']
)
