
version: '2.1'

orbs:
  python: circleci/python@2.1.1

workflows:
  main:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/

jobs:
  build:
    docker:
      - image: cimg/python:3.10-browsers
    executor: python/default
    steps:
      - checkout
      - run:
          name: Install library dependencies
          command: |
            sudo apt update
            sudo apt install libnotify-dev
            sudo apt install libgtk-3-dev
            sudo apt-get install -y  libsdl2-dev
            pip install --upgrade pip
            pip install wheel==0.38.4
            pip install setuptools==65.7.0
            pip install six==1.16.0
            pip install attrdict3
            pip install -v -U -f https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-22.04  wxPython
            pip install PyGithub~=1.57
            pip install todoist-api-python~=2.0.2
            pip install html-testRunner~=1.2.1
      - run:
            name: run tests
            command: | 
              scripts/runtests.sh
